In [1]:
import numpy as np

Given point in code

In [2]:
original_point = np.array([1, 2, 3])

According to the input information

In [3]:
# rotation degrees
rot_x = 0
rot_y = 45
rot_z = 0

# translation
trans_x = 3
trans_y = 2
trans_z = 1

### Rotation point in 3D

To rotate a 3D point, the following rotation matrixes is used:

$$
\mathbf{R_x} = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & cos(\theta) & sin(\theta) & 0 \\
0 & -sin(\theta) & cos(\theta) & 0 \\
0 & 0 & 0 & 1 
\end{bmatrix}
$$

$$
\mathbf{R_y} = \begin{bmatrix}
cos(\theta) & 0 & -sin(\theta) & 0 \\
0 & 1 & 0 & 0 \\
sin(\theta) & 0 & cos(\theta) & 0 \\
0 & 0 & 0 & 1 
\end{bmatrix}
$$

$$
\mathbf{R_z} = \begin{bmatrix}
cos(\theta) & -sin(\theta) & 0 & 0 \\
0 & 1 & 0 & 0 \\
sin(\theta) & cos(\theta) & 0 &  0 \\
0 & 0 & 0 & 1 
\end{bmatrix}
$$

It is assumed that for each rotation, the corresponding $\theta$ is in radians and the point homogenous as

$$
\mathbf{x} = \begin{bmatrix}
y \\
y \\
z \\
1 
\end{bmatrix}
$$

and the transformation is applied as: -

$$
y = \mathbf{R_z}\mathbf{R_y}\mathbf{R_x}x
$$

In [4]:
# converting degrees to radians
rot_x_rad = np.deg2rad(rot_x)
rot_y_rad = np.deg2rad(rot_y)
rot_z_rad = np.deg2rad(rot_z)

In [5]:
rot_x_matrix = np.array([
    [1, 0, 0, 0],
    [0, np.cos(rot_x_rad), -np.sin(rot_x_rad), 0],
    [0, np.sin(rot_x_rad), np.cos(rot_x_rad), 0],
    [0, 0, 0, 1]
])
rot_y_matrix = np.array([
    [np.cos(rot_y_rad), 0, -np.sin(rot_y_rad), 0],
    [0, 1, 0, 0],
    [np.sin(rot_y_rad), 0, np.cos(rot_y_rad), 0],
    [0, 0, 0, 1]
])
rot_z_matrix = np.array([
    [np.cos(rot_z_rad), -np.sin(rot_z_rad), 0, 0],
    [np.sin(rot_z_rad), np.cos(rot_z_rad), 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])
print("Rotation matrices:")
print("X axis:")
print(rot_x_matrix)
print("\nY axis:")
print(rot_y_matrix)
print("\nZ axis:")
print(rot_z_matrix)

Rotation matrices:
X axis:
[[ 1.  0.  0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Y axis:
[[ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]

Z axis:
[[ 1. -0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


### Translate point in 3D

To translate a 3D point, the following translation matrix is used:

$$
\mathbf{T} = \begin{bmatrix}
1 & 0 & 0 & t_x \\
0 & 1 & 0 & t_y \\
0 & 0 & 1 & t_z \\
0 & 0 & 0 & 1 
\end{bmatrix}
$$

and the point is assumed to be homogenous as

$$
\mathbf{x} = \begin{bmatrix}
y \\
y \\
z \\
1 
\end{bmatrix}
$$

and the transformation is applied as: -

$$
y = \mathbf{T}x
$$

In [6]:
translation_matrix = np.array([
    [1, 0, 0, trans_x],
    [0, 1, 0, trans_y],
    [0, 0, 1, trans_z],
    [0, 0, 0, 1]
])
print("Translation Matrix: \n", translation_matrix)

Translation Matrix: 
 [[1 0 0 3]
 [0 1 0 2]
 [0 0 1 1]
 [0 0 0 1]]


### Applying the transformations to the point using the rotation and translation matrixes

$$
y = \mathbf{T}\mathbf{R_z}\mathbf{R_y}\mathbf{R_x}x
$$

In [7]:
transformation_matrix = translation_matrix @ rot_z_matrix @ rot_y_matrix @ rot_x_matrix
print("Transformation Matrix: \n", transformation_matrix)

Transformation Matrix: 
 [[ 0.70710678  0.         -0.70710678  3.        ]
 [ 0.          1.          0.          2.        ]
 [ 0.70710678  0.          0.70710678  1.        ]
 [ 0.          0.          0.          1.        ]]


In [8]:
transformed_point = np.dot(transformation_matrix, np.append(original_point, 1))
transformed_point = transformed_point[:3]

In [9]:
print("Transformed point: ", transformed_point)

Transformed point:  [1.58578644 4.         3.82842712]
